### PR TITLE
Setup Travis, and eat my own dog food

### PR DESCRIPTION
**Pull request by hectorj**

### CODE REVIEW

**Comment by R-BeepBop** [comment]
<details><summary>42 violation(s) found in checkstyle report.</summary><ul><li><br><pre>Potential hardcoded credentials,HIGH,LOW</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>duplicate of glue/source_basichtml_gocover.go:1-37</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>duplicate of glue/source_basichtml_gotest.go:1-37</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>duplicate of glue/source_basichtml_checkstyle.go:1-37</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>duplicate of glue/target_basichtml_github.go:11-53</pre></li><li><br><pre>duplicate of glue/target_basichtml_file.go:11-53</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>duplicate of sources/basichtml/gocover/source.go:1-34</pre></li><li><br><pre>duplicate of sources/basichtml/gotest/source.go:1-34</pre></li><li><br><pre>duplicate of sources/basichtml/checkstyle/source.go:1-34</pre></li><li><br><pre>duplicate of sources/raw/interface.go:1-15</pre></li><li><br><pre>duplicate of sources/gocover/interface.go:1-13</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>duplicate of sources/gotest/interface.go:1-13</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>duplicate of sources/checkstyle/interface.go:1-13</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>duplicate of sources/basichtml/interface.go:1-15</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li></ul></details><hr>

**Comment by R-BeepBop** [comment]
<details><summary>42 violation(s) found in checkstyle report.</summary><ul><li><br><pre>Potential hardcoded credentials,HIGH,LOW</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>duplicate of glue/source_basichtml_gocover.go:1-37</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>duplicate of glue/source_basichtml_gotest.go:1-37</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>duplicate of glue/source_basichtml_checkstyle.go:1-37</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>duplicate of glue/target_basichtml_github.go:11-53</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>duplicate of glue/target_basichtml_file.go:11-53</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>duplicate of sources/basichtml/gocover/source.go:1-34</pre></li><li><br><pre>duplicate of sources/basichtml/gotest/source.go:1-34</pre></li><li><br><pre>duplicate of sources/basichtml/checkstyle/source.go:1-34</pre></li><li><br><pre>duplicate of sources/raw/interface.go:1-15</pre></li><li><br><pre>duplicate of sources/gocover/interface.go:1-13</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>duplicate of sources/gotest/interface.go:1-13</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>duplicate of sources/checkstyle/interface.go:1-13</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>duplicate of sources/basichtml/interface.go:1-15</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li><li><br><pre>file is not gofmted with -s</pre></li><li><br><pre>file is not goimported</pre></li></ul></details><hr>

**Comment by R-BeepBop** [comment]
<details open><summary>1 violation(s) found in checkstyle report.</summary><ul><li><br><pre>Potential hardcoded credentials,HIGH,LOW</pre></li></ul></details><hr>

**Comment by R-BeepBop** [comment]
<details open><summary>1 violation(s) found in checkstyle report.</summary><ul><li>File "ir-blaster/internal/glue/github_config.go", line 10<br><pre>Potential hardcoded credentials,HIGH,LOW</pre></li></ul></details><hr>

**Comment by R-BeepBop** [comment]
No violations in checkstyle report.<hr>

**Comment by hectorj** [comment]
Ok, it's not perfect but the travis setup is working.

To be done in next PRs: 
- [x] don't try to push to github PR if we're not testing a PR
- [x] have a "everything is ok" message for PHPUnit
- [ ] fail the build if one of the subtasks fails

**Pull request merged**
